import { IForecast } from '../types/forecastWeather';
import type { PayloadAction } from '@reduxjs/toolkit';
import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { ILocation, ICurrentWeather } from '../types/forecastWeather';

export interface IForecastWeather {
    location: ILocation;
    forecast: IForecast;
    current: ICurrentWeather;
}

const initialState: IForecastWeather = {
    "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "tz_id": "Europe/London",
        "localtime_epoch": 1688979133,
        "localtime": "2023-07-10 9:52"
    },
    "current": {
        "last_updated_epoch": 1688978700,
        "last_updated": "2023-07-10 09:45",
        "temp_c": 19,
        "temp_f": 66.2,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 10.5,
        "wind_kph": 16.9,
        "wind_degree": 240,
        "wind_dir": "WSW",
        "pressure_mb": 1021,
        "pressure_in": 30.15,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 68,
        "cloud": 50,
        "feelslike_c": 19,
        "feelslike_f": 66.2,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 6,
        "gust_mph": 12.1,
        "gust_kph": 19.4
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2023-07-10",
          "date_epoch": 1688947200,
          "day": {
            "maxtemp_c": 24.1,
            "maxtemp_f": 75.4,
            "mintemp_c": 14.4,
            "mintemp_f": 57.9,
            "avgtemp_c": 19.6,
            "avgtemp_f": 67.2,
            "maxwind_mph": 15.4,
            "maxwind_kph": 24.8,
            "totalprecip_mm": 0,
            "totalprecip_in": 0,
            "totalsnow_cm": 0,
            "avgvis_km": 10,
            "avgvis_miles": 6,
            "avghumidity": 61,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 0,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "uv": 5
          },
          "astro": {
            "sunrise": "04:55 AM",
            "sunset": "09:16 PM",
            "moonrise": "12:26 AM",
            "moonset": "02:01 PM",
            "moon_phase": "Last Quarter",
            "moon_illumination": "51",
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1688943600,
              "time": "2023-07-10 00:00",
              "temp_c": 16.1,
              "temp_f": 61,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 223,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 74,
              "cloud": 6,
              "feelslike_c": 16.1,
              "feelslike_f": 61,
              "windchill_c": 16.1,
              "windchill_f": 61,
              "heatindex_c": 16.1,
              "heatindex_f": 61,
              "dewpoint_c": 11.5,
              "dewpoint_f": 52.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.2,
              "gust_kph": 18,
              "uv": 1
            },
            {
              "time_epoch": 1688947200,
              "time": "2023-07-10 01:00",
              "temp_c": 15.7,
              "temp_f": 60.3,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 232,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 75,
              "cloud": 100,
              "feelslike_c": 15.7,
              "feelslike_f": 60.3,
              "windchill_c": 15.7,
              "windchill_f": 60.3,
              "heatindex_c": 15.7,
              "heatindex_f": 60.3,
              "dewpoint_c": 11.3,
              "dewpoint_f": 52.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 1
            },
            {
              "time_epoch": 1688950800,
              "time": "2023-07-10 02:00",
              "temp_c": 15.3,
              "temp_f": 59.5,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.9,
              "wind_kph": 11.2,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 76,
              "cloud": 8,
              "feelslike_c": 15.3,
              "feelslike_f": 59.5,
              "windchill_c": 15.3,
              "windchill_f": 59.5,
              "heatindex_c": 15.3,
              "heatindex_f": 59.5,
              "dewpoint_c": 11.2,
              "dewpoint_f": 52.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.1,
              "gust_kph": 16.2,
              "uv": 1
            },
            {
              "time_epoch": 1688954400,
              "time": "2023-07-10 03:00",
              "temp_c": 14.6,
              "temp_f": 58.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 79,
              "cloud": 17,
              "feelslike_c": 13.9,
              "feelslike_f": 57,
              "windchill_c": 13.9,
              "windchill_f": 57,
              "heatindex_c": 14.6,
              "heatindex_f": 58.3,
              "dewpoint_c": 11.1,
              "dewpoint_f": 52,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.7,
              "gust_kph": 17.3,
              "uv": 1
            },
            {
              "time_epoch": 1688958000,
              "time": "2023-07-10 04:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 6.9,
              "wind_kph": 11.2,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 81,
              "cloud": 8,
              "feelslike_c": 13.3,
              "feelslike_f": 55.9,
              "windchill_c": 13.3,
              "windchill_f": 55.9,
              "heatindex_c": 14,
              "heatindex_f": 57.2,
              "dewpoint_c": 10.9,
              "dewpoint_f": 51.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11,
              "gust_kph": 17.6,
              "uv": 1
            },
            {
              "time_epoch": 1688961600,
              "time": "2023-07-10 05:00",
              "temp_c": 14.3,
              "temp_f": 57.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 224,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 81,
              "cloud": 4,
              "feelslike_c": 13.9,
              "feelslike_f": 57,
              "windchill_c": 13.9,
              "windchill_f": 57,
              "heatindex_c": 14.3,
              "heatindex_f": 57.7,
              "dewpoint_c": 11.1,
              "dewpoint_f": 52,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.7,
              "gust_kph": 14,
              "uv": 4
            },
            {
              "time_epoch": 1688965200,
              "time": "2023-07-10 06:00",
              "temp_c": 15.8,
              "temp_f": 60.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 8.1,
              "wind_kph": 13,
              "wind_degree": 223,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 76,
              "cloud": 6,
              "feelslike_c": 15.8,
              "feelslike_f": 60.4,
              "windchill_c": 15.8,
              "windchill_f": 60.4,
              "heatindex_c": 15.8,
              "heatindex_f": 60.4,
              "dewpoint_c": 11.5,
              "dewpoint_f": 52.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 5
            },
            {
              "time_epoch": 1688968800,
              "time": "2023-07-10 07:00",
              "temp_c": 17.5,
              "temp_f": 63.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 69,
              "cloud": 27,
              "feelslike_c": 17.5,
              "feelslike_f": 63.5,
              "windchill_c": 17.5,
              "windchill_f": 63.5,
              "heatindex_c": 17.5,
              "heatindex_f": 63.5,
              "dewpoint_c": 11.8,
              "dewpoint_f": 53.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 5
            },
            {
              "time_epoch": 1688972400,
              "time": "2023-07-10 08:00",
              "temp_c": 18.8,
              "temp_f": 65.8,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.3,
              "wind_kph": 16.6,
              "wind_degree": 218,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 63,
              "cloud": 41,
              "feelslike_c": 18.8,
              "feelslike_f": 65.8,
              "windchill_c": 18.8,
              "windchill_f": 65.8,
              "heatindex_c": 18.8,
              "heatindex_f": 65.8,
              "dewpoint_c": 11.5,
              "dewpoint_f": 52.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.9,
              "gust_kph": 19.1,
              "uv": 5
            },
            {
              "time_epoch": 1688976000,
              "time": "2023-07-10 09:00",
              "temp_c": 20.4,
              "temp_f": 68.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 216,
              "wind_dir": "SW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 54,
              "cloud": 31,
              "feelslike_c": 20.4,
              "feelslike_f": 68.7,
              "windchill_c": 20.4,
              "windchill_f": 68.7,
              "heatindex_c": 20.4,
              "heatindex_f": 68.7,
              "dewpoint_c": 10.9,
              "dewpoint_f": 51.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.1,
              "gust_kph": 19.4,
              "uv": 6
            },
            {
              "time_epoch": 1688979600,
              "time": "2023-07-10 10:00",
              "temp_c": 21.8,
              "temp_f": 71.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 210,
              "wind_dir": "SSW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 48,
              "cloud": 27,
              "feelslike_c": 21.8,
              "feelslike_f": 71.2,
              "windchill_c": 21.8,
              "windchill_f": 71.2,
              "heatindex_c": 24.3,
              "heatindex_f": 75.7,
              "dewpoint_c": 10.2,
              "dewpoint_f": 50.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.4,
              "gust_kph": 21.6,
              "uv": 6
            },
            {
              "time_epoch": 1688983200,
              "time": "2023-07-10 11:00",
              "temp_c": 23.3,
              "temp_f": 73.9,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 1020,
              "pressure_in": 30.13,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 43,
              "cloud": 38,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 23.3,
              "windchill_f": 73.9,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 10,
              "dewpoint_f": 50,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.6,
              "gust_kph": 22,
              "uv": 6
            },
            {
              "time_epoch": 1688986800,
              "time": "2023-07-10 12:00",
              "temp_c": 24,
              "temp_f": 75.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 13,
              "wind_kph": 20.9,
              "wind_degree": 207,
              "wind_dir": "SSW",
              "pressure_mb": 1020,
              "pressure_in": 30.11,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 40,
              "cloud": 32,
              "feelslike_c": 24.8,
              "feelslike_f": 76.6,
              "windchill_c": 24,
              "windchill_f": 75.2,
              "heatindex_c": 24.8,
              "heatindex_f": 76.6,
              "dewpoint_c": 9.7,
              "dewpoint_f": 49.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15,
              "gust_kph": 24.1,
              "uv": 6
            },
            {
              "time_epoch": 1688990400,
              "time": "2023-07-10 13:00",
              "temp_c": 24,
              "temp_f": 75.2,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 14.1,
              "wind_kph": 22.7,
              "wind_degree": 207,
              "wind_dir": "SSW",
              "pressure_mb": 1019,
              "pressure_in": 30.09,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 40,
              "cloud": 81,
              "feelslike_c": 24.8,
              "feelslike_f": 76.6,
              "windchill_c": 24,
              "windchill_f": 75.2,
              "heatindex_c": 24.8,
              "heatindex_f": 76.6,
              "dewpoint_c": 9.8,
              "dewpoint_f": 49.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.1,
              "gust_kph": 25.9,
              "uv": 5
            },
            {
              "time_epoch": 1688994000,
              "time": "2023-07-10 14:00",
              "temp_c": 23.7,
              "temp_f": 74.7,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 15.4,
              "wind_kph": 24.8,
              "wind_degree": 207,
              "wind_dir": "SSW",
              "pressure_mb": 1019,
              "pressure_in": 30.08,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 41,
              "cloud": 83,
              "feelslike_c": 24.7,
              "feelslike_f": 76.5,
              "windchill_c": 23.7,
              "windchill_f": 74.7,
              "heatindex_c": 24.7,
              "heatindex_f": 76.5,
              "dewpoint_c": 9.7,
              "dewpoint_f": 49.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.7,
              "gust_kph": 28.4,
              "uv": 5
            },
            {
              "time_epoch": 1688997600,
              "time": "2023-07-10 15:00",
              "temp_c": 22.6,
              "temp_f": 72.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 14.5,
              "wind_kph": 23.4,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 1019,
              "pressure_in": 30.08,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 45,
              "cloud": 11,
              "feelslike_c": 24.4,
              "feelslike_f": 75.9,
              "windchill_c": 22.6,
              "windchill_f": 72.7,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 10,
              "dewpoint_f": 50,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.8,
              "gust_kph": 27,
              "uv": 6
            },
            {
              "time_epoch": 1689001200,
              "time": "2023-07-10 16:00",
              "temp_c": 22.9,
              "temp_f": 73.2,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 14.5,
              "wind_kph": 23.4,
              "wind_degree": 215,
              "wind_dir": "SW",
              "pressure_mb": 1018,
              "pressure_in": 30.06,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 43,
              "cloud": 77,
              "feelslike_c": 24.4,
              "feelslike_f": 75.9,
              "windchill_c": 22.9,
              "windchill_f": 73.2,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 9.7,
              "dewpoint_f": 49.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.8,
              "gust_kph": 27,
              "uv": 5
            },
            {
              "time_epoch": 1689004800,
              "time": "2023-07-10 17:00",
              "temp_c": 22.4,
              "temp_f": 72.3,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 13.2,
              "wind_kph": 21.2,
              "wind_degree": 217,
              "wind_dir": "SW",
              "pressure_mb": 1018,
              "pressure_in": 30.05,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 51,
              "cloud": 37,
              "feelslike_c": 24.5,
              "feelslike_f": 76.1,
              "windchill_c": 22.4,
              "windchill_f": 72.3,
              "heatindex_c": 24.5,
              "heatindex_f": 76.1,
              "dewpoint_c": 11.7,
              "dewpoint_f": 53.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.2,
              "gust_kph": 24.5,
              "uv": 6
            },
            {
              "time_epoch": 1689008400,
              "time": "2023-07-10 18:00",
              "temp_c": 22.2,
              "temp_f": 72,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 12.3,
              "wind_kph": 19.8,
              "wind_degree": 212,
              "wind_dir": "SSW",
              "pressure_mb": 1017,
              "pressure_in": 30.03,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 54,
              "cloud": 24,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 22.2,
              "windchill_f": 72,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 12.5,
              "dewpoint_f": 54.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 6
            },
            {
              "time_epoch": 1689012000,
              "time": "2023-07-10 19:00",
              "temp_c": 21.5,
              "temp_f": 70.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 1017,
              "pressure_in": 30.03,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 59,
              "cloud": 30,
              "feelslike_c": 21.5,
              "feelslike_f": 70.7,
              "windchill_c": 21.5,
              "windchill_f": 70.7,
              "heatindex_c": 24.5,
              "heatindex_f": 76.1,
              "dewpoint_c": 13.1,
              "dewpoint_f": 55.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.2,
              "gust_kph": 21.2,
              "uv": 6
            },
            {
              "time_epoch": 1689015600,
              "time": "2023-07-10 20:00",
              "temp_c": 19.7,
              "temp_f": 67.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 196,
              "wind_dir": "SSW",
              "pressure_mb": 1016,
              "pressure_in": 30.01,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 64,
              "cloud": 49,
              "feelslike_c": 19.7,
              "feelslike_f": 67.5,
              "windchill_c": 19.7,
              "windchill_f": 67.5,
              "heatindex_c": 19.7,
              "heatindex_f": 67.5,
              "dewpoint_c": 12.6,
              "dewpoint_f": 54.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 5
            },
            {
              "time_epoch": 1689019200,
              "time": "2023-07-10 21:00",
              "temp_c": 18.9,
              "temp_f": 66,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 192,
              "wind_dir": "SSW",
              "pressure_mb": 1016,
              "pressure_in": 30,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 66,
              "cloud": 43,
              "feelslike_c": 18.9,
              "feelslike_f": 66,
              "windchill_c": 18.9,
              "windchill_f": 66,
              "heatindex_c": 18.9,
              "heatindex_f": 66,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.4,
              "gust_kph": 21.6,
              "uv": 5
            },
            {
              "time_epoch": 1689022800,
              "time": "2023-07-10 22:00",
              "temp_c": 18.9,
              "temp_f": 66,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 195,
              "wind_dir": "SSW",
              "pressure_mb": 1016,
              "pressure_in": 29.99,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 66,
              "cloud": 100,
              "feelslike_c": 18.9,
              "feelslike_f": 66,
              "windchill_c": 18.9,
              "windchill_f": 66,
              "heatindex_c": 18.9,
              "heatindex_f": 66,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.2,
              "gust_kph": 21.2,
              "uv": 1
            },
            {
              "time_epoch": 1689026400,
              "time": "2023-07-10 23:00",
              "temp_c": 19,
              "temp_f": 66.2,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 192,
              "wind_dir": "SSW",
              "pressure_mb": 1015,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 66,
              "cloud": 100,
              "feelslike_c": 19,
              "feelslike_f": 66.2,
              "windchill_c": 19,
              "windchill_f": 66.2,
              "heatindex_c": 19,
              "heatindex_f": 66.2,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13,
              "gust_kph": 20.9,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-07-11",
          "date_epoch": 1689033600,
          "day": {
            "maxtemp_c": 20.2,
            "maxtemp_f": 68.4,
            "mintemp_c": 15,
            "mintemp_f": 59,
            "avgtemp_c": 17.3,
            "avgtemp_f": 63.1,
            "maxwind_mph": 13.4,
            "maxwind_kph": 21.6,
            "totalprecip_mm": 6.3,
            "totalprecip_in": 0.25,
            "totalsnow_cm": 0,
            "avgvis_km": 9,
            "avgvis_miles": 5,
            "avghumidity": 82,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 85,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 4
          },
          "astro": {
            "sunrise": "04:56 AM",
            "sunset": "09:16 PM",
            "moonrise": "12:39 AM",
            "moonset": "03:22 PM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": "40",
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1689030000,
              "time": "2023-07-11 00:00",
              "temp_c": 18.7,
              "temp_f": 65.7,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 184,
              "wind_dir": "S",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 66,
              "cloud": 100,
              "feelslike_c": 18.7,
              "feelslike_f": 65.7,
              "windchill_c": 18.7,
              "windchill_f": 65.7,
              "heatindex_c": 18.7,
              "heatindex_f": 65.7,
              "dewpoint_c": 12.3,
              "dewpoint_f": 54.1,
              "will_it_rain": 0,
              "chance_of_rain": 68,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.8,
              "gust_kph": 23.8,
              "uv": 1
            },
            {
              "time_epoch": 1689033600,
              "time": "2023-07-11 01:00",
              "temp_c": 18.5,
              "temp_f": 65.3,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 182,
              "wind_dir": "S",
              "pressure_mb": 1013,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 68,
              "cloud": 92,
              "feelslike_c": 18.5,
              "feelslike_f": 65.3,
              "windchill_c": 18.5,
              "windchill_f": 65.3,
              "heatindex_c": 18.5,
              "heatindex_f": 65.3,
              "dewpoint_c": 12.5,
              "dewpoint_f": 54.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.8,
              "gust_kph": 27,
              "uv": 1
            },
            {
              "time_epoch": 1689037200,
              "time": "2023-07-11 02:00",
              "temp_c": 18.4,
              "temp_f": 65.1,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 192,
              "wind_dir": "SSW",
              "pressure_mb": 1012,
              "pressure_in": 29.88,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 71,
              "cloud": 100,
              "feelslike_c": 18.4,
              "feelslike_f": 65.1,
              "windchill_c": 18.4,
              "windchill_f": 65.1,
              "heatindex_c": 18.4,
              "heatindex_f": 65.1,
              "dewpoint_c": 13.1,
              "dewpoint_f": 55.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.2,
              "gust_kph": 31,
              "uv": 1
            },
            {
              "time_epoch": 1689040800,
              "time": "2023-07-11 03:00",
              "temp_c": 18.4,
              "temp_f": 65.1,
              "is_day": 0,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                "code": 1063
              },
              "wind_mph": 13,
              "wind_kph": 20.9,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 78,
              "cloud": 100,
              "feelslike_c": 18.4,
              "feelslike_f": 65.1,
              "windchill_c": 18.4,
              "windchill_f": 65.1,
              "heatindex_c": 18.4,
              "heatindex_f": 65.1,
              "dewpoint_c": 14.4,
              "dewpoint_f": 57.9,
              "will_it_rain": 0,
              "chance_of_rain": 65,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.2,
              "gust_kph": 31,
              "uv": 1
            },
            {
              "time_epoch": 1689044400,
              "time": "2023-07-11 04:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 207,
              "wind_dir": "SSW",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 86,
              "cloud": 100,
              "feelslike_c": 17.9,
              "feelslike_f": 64.2,
              "windchill_c": 17.9,
              "windchill_f": 64.2,
              "heatindex_c": 17.9,
              "heatindex_f": 64.2,
              "dewpoint_c": 15.5,
              "dewpoint_f": 59.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.1,
              "gust_kph": 29.2,
              "uv": 1
            },
            {
              "time_epoch": 1689048000,
              "time": "2023-07-11 05:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 13.4,
              "wind_kph": 21.6,
              "wind_degree": 208,
              "wind_dir": "SSW",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 87,
              "cloud": 100,
              "feelslike_c": 17.9,
              "feelslike_f": 64.2,
              "windchill_c": 17.9,
              "windchill_f": 64.2,
              "heatindex_c": 17.9,
              "heatindex_f": 64.2,
              "dewpoint_c": 15.7,
              "dewpoint_f": 60.3,
              "will_it_rain": 1,
              "chance_of_rain": 72,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 19.2,
              "gust_kph": 31,
              "uv": 4
            },
            {
              "time_epoch": 1689051600,
              "time": "2023-07-11 06:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 1,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                "code": 1183
              },
              "wind_mph": 12.1,
              "wind_kph": 19.4,
              "wind_degree": 221,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0.8,
              "precip_in": 0.03,
              "humidity": 88,
              "cloud": 100,
              "feelslike_c": 17.9,
              "feelslike_f": 64.2,
              "windchill_c": 17.9,
              "windchill_f": 64.2,
              "heatindex_c": 17.9,
              "heatindex_f": 64.2,
              "dewpoint_c": 15.8,
              "dewpoint_f": 60.4,
              "will_it_rain": 0,
              "chance_of_rain": 70,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 16.6,
              "gust_kph": 26.6,
              "uv": 4
            },
            {
              "time_epoch": 1689055200,
              "time": "2023-07-11 07:00",
              "temp_c": 17.2,
              "temp_f": 63,
              "is_day": 1,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                "code": 1183
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 1.3,
              "precip_in": 0.05,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": 17.2,
              "feelslike_f": 63,
              "windchill_c": 17.2,
              "windchill_f": 63,
              "heatindex_c": 17.2,
              "heatindex_f": 63,
              "dewpoint_c": 16.4,
              "dewpoint_f": 61.5,
              "will_it_rain": 1,
              "chance_of_rain": 88,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 14.3,
              "gust_kph": 23,
              "uv": 4
            },
            {
              "time_epoch": 1689058800,
              "time": "2023-07-11 08:00",
              "temp_c": 17.2,
              "temp_f": 63,
              "is_day": 1,
              "condition": {
                "text": "Patchy light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/293.png",
                "code": 1180
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 230,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0.8,
              "precip_in": 0.03,
              "humidity": 92,
              "cloud": 65,
              "feelslike_c": 17.2,
              "feelslike_f": 63,
              "windchill_c": 17.2,
              "windchill_f": 63,
              "heatindex_c": 17.2,
              "heatindex_f": 63,
              "dewpoint_c": 15.8,
              "dewpoint_f": 60.4,
              "will_it_rain": 1,
              "chance_of_rain": 83,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 13.4,
              "gust_kph": 21.6,
              "uv": 4
            },
            {
              "time_epoch": 1689062400,
              "time": "2023-07-11 09:00",
              "temp_c": 17.1,
              "temp_f": 62.8,
              "is_day": 1,
              "condition": {
                "text": "Patchy light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/293.png",
                "code": 1180
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 227,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 1.6,
              "precip_in": 0.06,
              "humidity": 88,
              "cloud": 65,
              "feelslike_c": 17.1,
              "feelslike_f": 62.8,
              "windchill_c": 17.1,
              "windchill_f": 62.8,
              "heatindex_c": 17.1,
              "heatindex_f": 62.8,
              "dewpoint_c": 15.1,
              "dewpoint_f": 59.2,
              "will_it_rain": 1,
              "chance_of_rain": 88,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 13.9,
              "gust_kph": 22.3,
              "uv": 4
            },
            {
              "time_epoch": 1689066000,
              "time": "2023-07-11 10:00",
              "temp_c": 17.4,
              "temp_f": 63.3,
              "is_day": 1,
              "condition": {
                "text": "Patchy light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/263.png",
                "code": 1150
              },
              "wind_mph": 10.3,
              "wind_kph": 16.6,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 83,
              "cloud": 67,
              "feelslike_c": 17.4,
              "feelslike_f": 63.3,
              "windchill_c": 17.4,
              "windchill_f": 63.3,
              "heatindex_c": 17.4,
              "heatindex_f": 63.3,
              "dewpoint_c": 14.4,
              "dewpoint_f": 57.9,
              "will_it_rain": 0,
              "chance_of_rain": 68,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 5,
              "vis_miles": 3,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 4
            },
            {
              "time_epoch": 1689069600,
              "time": "2023-07-11 11:00",
              "temp_c": 19.9,
              "temp_f": 67.8,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 222,
              "wind_dir": "SW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 67,
              "cloud": 70,
              "feelslike_c": 19.9,
              "feelslike_f": 67.8,
              "windchill_c": 19.9,
              "windchill_f": 67.8,
              "heatindex_c": 19.9,
              "heatindex_f": 67.8,
              "dewpoint_c": 13.5,
              "dewpoint_f": 56.3,
              "will_it_rain": 1,
              "chance_of_rain": 74,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 13.2,
              "gust_kph": 21.2,
              "uv": 4
            },
            {
              "time_epoch": 1689073200,
              "time": "2023-07-11 12:00",
              "temp_c": 22.8,
              "temp_f": 73,
              "is_day": 1,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                "code": 1153
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 220,
              "wind_dir": "SW",
              "pressure_mb": 1008,
              "pressure_in": 29.78,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "humidity": 47,
              "cloud": 82,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 22.8,
              "windchill_f": 73,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 10.9,
              "dewpoint_f": 51.6,
              "will_it_rain": 0,
              "chance_of_rain": 61,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 14.3,
              "gust_kph": 23,
              "uv": 5
            },
            {
              "time_epoch": 1689076800,
              "time": "2023-07-11 13:00",
              "temp_c": 24.2,
              "temp_f": 75.6,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 13.6,
              "wind_kph": 22,
              "wind_degree": 224,
              "wind_dir": "SW",
              "pressure_mb": 1008,
              "pressure_in": 29.76,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 40,
              "cloud": 48,
              "feelslike_c": 24.9,
              "feelslike_f": 76.8,
              "windchill_c": 24.2,
              "windchill_f": 75.6,
              "heatindex_c": 24.9,
              "heatindex_f": 76.8,
              "dewpoint_c": 9.8,
              "dewpoint_f": 49.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 6
            },
            {
              "time_epoch": 1689080400,
              "time": "2023-07-11 14:00",
              "temp_c": 24.3,
              "temp_f": 75.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 15,
              "wind_kph": 24.1,
              "wind_degree": 220,
              "wind_dir": "SW",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 39,
              "cloud": 48,
              "feelslike_c": 24.9,
              "feelslike_f": 76.8,
              "windchill_c": 24.3,
              "windchill_f": 75.7,
              "heatindex_c": 24.9,
              "heatindex_f": 76.8,
              "dewpoint_c": 9.6,
              "dewpoint_f": 49.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.2,
              "gust_kph": 27.7,
              "uv": 6
            },
            {
              "time_epoch": 1689084000,
              "time": "2023-07-11 15:00",
              "temp_c": 23,
              "temp_f": 73.4,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 15.9,
              "wind_kph": 25.6,
              "wind_degree": 214,
              "wind_dir": "SW",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 45,
              "cloud": 57,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 23,
              "windchill_f": 73.4,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 10.6,
              "dewpoint_f": 51.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.3,
              "gust_kph": 29.5,
              "uv": 6
            },
            {
              "time_epoch": 1689087600,
              "time": "2023-07-11 16:00",
              "temp_c": 21.6,
              "temp_f": 70.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 13.6,
              "wind_kph": 22,
              "wind_degree": 218,
              "wind_dir": "SW",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 55,
              "cloud": 9,
              "feelslike_c": 21.6,
              "feelslike_f": 70.9,
              "windchill_c": 21.6,
              "windchill_f": 70.9,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 12.2,
              "dewpoint_f": 54,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 6
            },
            {
              "time_epoch": 1689091200,
              "time": "2023-07-11 17:00",
              "temp_c": 21.5,
              "temp_f": 70.7,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 14.3,
              "wind_kph": 23,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 1007,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 55,
              "cloud": 64,
              "feelslike_c": 21.5,
              "feelslike_f": 70.7,
              "windchill_c": 21.5,
              "windchill_f": 70.7,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 12.1,
              "dewpoint_f": 53.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.6,
              "gust_kph": 26.6,
              "uv": 5
            },
            {
              "time_epoch": 1689094800,
              "time": "2023-07-11 18:00",
              "temp_c": 20.7,
              "temp_f": 69.3,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1007,
              "pressure_in": 29.74,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 59,
              "cloud": 49,
              "feelslike_c": 20.7,
              "feelslike_f": 69.3,
              "windchill_c": 20.7,
              "windchill_f": 69.3,
              "heatindex_c": 20.7,
              "heatindex_f": 69.3,
              "dewpoint_c": 12.5,
              "dewpoint_f": 54.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.3,
              "gust_kph": 23,
              "uv": 6
            },
            {
              "time_epoch": 1689098400,
              "time": "2023-07-11 19:00",
              "temp_c": 19.6,
              "temp_f": 67.3,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 12.5,
              "wind_kph": 20.2,
              "wind_degree": 225,
              "wind_dir": "SW",
              "pressure_mb": 1007,
              "pressure_in": 29.74,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 65,
              "cloud": 45,
              "feelslike_c": 19.6,
              "feelslike_f": 67.3,
              "windchill_c": 19.6,
              "windchill_f": 67.3,
              "heatindex_c": 19.6,
              "heatindex_f": 67.3,
              "dewpoint_c": 12.9,
              "dewpoint_f": 55.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 5
            },
            {
              "time_epoch": 1689102000,
              "time": "2023-07-11 20:00",
              "temp_c": 18.2,
              "temp_f": 64.8,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 230,
              "wind_dir": "SW",
              "pressure_mb": 1007,
              "pressure_in": 29.74,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 71,
              "cloud": 78,
              "feelslike_c": 18.2,
              "feelslike_f": 64.8,
              "windchill_c": 18.2,
              "windchill_f": 64.8,
              "heatindex_c": 18.2,
              "heatindex_f": 64.8,
              "dewpoint_c": 12.9,
              "dewpoint_f": 55.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.4,
              "gust_kph": 24.8,
              "uv": 4
            },
            {
              "time_epoch": 1689105600,
              "time": "2023-07-11 21:00",
              "temp_c": 17.3,
              "temp_f": 63.1,
              "is_day": 1,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 77,
              "cloud": 99,
              "feelslike_c": 17.3,
              "feelslike_f": 63.1,
              "windchill_c": 17.3,
              "windchill_f": 63.1,
              "heatindex_c": 17.3,
              "heatindex_f": 63.1,
              "dewpoint_c": 13.3,
              "dewpoint_f": 55.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.4,
              "gust_kph": 24.8,
              "uv": 4
            },
            {
              "time_epoch": 1689109200,
              "time": "2023-07-11 22:00",
              "temp_c": 16.6,
              "temp_f": 61.9,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 235,
              "wind_dir": "SW",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 81,
              "cloud": 89,
              "feelslike_c": 16.6,
              "feelslike_f": 61.9,
              "windchill_c": 16.6,
              "windchill_f": 61.9,
              "heatindex_c": 16.6,
              "heatindex_f": 61.9,
              "dewpoint_c": 13.4,
              "dewpoint_f": 56.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.9,
              "gust_kph": 25.6,
              "uv": 1
            },
            {
              "time_epoch": 1689112800,
              "time": "2023-07-11 23:00",
              "temp_c": 16.1,
              "temp_f": 61,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 240,
              "wind_dir": "WSW",
              "pressure_mb": 1008,
              "pressure_in": 29.75,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 84,
              "cloud": 71,
              "feelslike_c": 16.1,
              "feelslike_f": 61,
              "windchill_c": 16.1,
              "windchill_f": 61,
              "heatindex_c": 16.1,
              "heatindex_f": 61,
              "dewpoint_c": 13.4,
              "dewpoint_f": 56.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-07-12",
          "date_epoch": 1689120000,
          "day": {
            "maxtemp_c": 21,
            "maxtemp_f": 69.8,
            "mintemp_c": 14.4,
            "mintemp_f": 57.9,
            "avgtemp_c": 17.1,
            "avgtemp_f": 62.8,
            "maxwind_mph": 14.3,
            "maxwind_kph": 23,
            "totalprecip_mm": 5.9,
            "totalprecip_in": 0.23,
            "totalsnow_cm": 0,
            "avgvis_km": 9.8,
            "avgvis_miles": 6,
            "avghumidity": 74,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 88,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 4
          },
          "astro": {
            "sunrise": "04:57 AM",
            "sunset": "09:15 PM",
            "moonrise": "12:55 AM",
            "moonset": "04:41 PM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": "30",
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1689116400,
              "time": "2023-07-12 00:00",
              "temp_c": 15.4,
              "temp_f": 59.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 248,
              "wind_dir": "WSW",
              "pressure_mb": 1008,
              "pressure_in": 29.76,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 84,
              "cloud": 58,
              "feelslike_c": 15.4,
              "feelslike_f": 59.7,
              "windchill_c": 15.4,
              "windchill_f": 59.7,
              "heatindex_c": 15.4,
              "heatindex_f": 59.7,
              "dewpoint_c": 12.7,
              "dewpoint_f": 54.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 1
            },
            {
              "time_epoch": 1689120000,
              "time": "2023-07-12 01:00",
              "temp_c": 14.8,
              "temp_f": 58.6,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 249,
              "wind_dir": "WSW",
              "pressure_mb": 1008,
              "pressure_in": 29.77,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 86,
              "cloud": 74,
              "feelslike_c": 13.8,
              "feelslike_f": 56.8,
              "windchill_c": 13.8,
              "windchill_f": 56.8,
              "heatindex_c": 14.8,
              "heatindex_f": 58.6,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.2,
              "gust_kph": 21.2,
              "uv": 1
            },
            {
              "time_epoch": 1689123600,
              "time": "2023-07-12 02:00",
              "temp_c": 14.3,
              "temp_f": 57.7,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 246,
              "wind_dir": "WSW",
              "pressure_mb": 1008,
              "pressure_in": 29.77,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 88,
              "cloud": 69,
              "feelslike_c": 13.3,
              "feelslike_f": 55.9,
              "windchill_c": 13.3,
              "windchill_f": 55.9,
              "heatindex_c": 14.3,
              "heatindex_f": 57.7,
              "dewpoint_c": 12.3,
              "dewpoint_f": 54.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.3,
              "gust_kph": 19.8,
              "uv": 1
            },
            {
              "time_epoch": 1689127200,
              "time": "2023-07-12 03:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 7.8,
              "wind_kph": 12.6,
              "wind_degree": 247,
              "wind_dir": "WSW",
              "pressure_mb": 1008,
              "pressure_in": 29.78,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 89,
              "cloud": 58,
              "feelslike_c": 13.1,
              "feelslike_f": 55.6,
              "windchill_c": 13.1,
              "windchill_f": 55.6,
              "heatindex_c": 14,
              "heatindex_f": 57.2,
              "dewpoint_c": 12.3,
              "dewpoint_f": 54.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11,
              "gust_kph": 17.6,
              "uv": 1
            },
            {
              "time_epoch": 1689130800,
              "time": "2023-07-12 04:00",
              "temp_c": 13.7,
              "temp_f": 56.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 8.3,
              "wind_kph": 13.3,
              "wind_degree": 240,
              "wind_dir": "WSW",
              "pressure_mb": 1009,
              "pressure_in": 29.79,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 90,
              "cloud": 62,
              "feelslike_c": 12.7,
              "feelslike_f": 54.9,
              "windchill_c": 12.7,
              "windchill_f": 54.9,
              "heatindex_c": 13.7,
              "heatindex_f": 56.7,
              "dewpoint_c": 12.1,
              "dewpoint_f": 53.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.6,
              "gust_kph": 18.7,
              "uv": 1
            },
            {
              "time_epoch": 1689134400,
              "time": "2023-07-12 05:00",
              "temp_c": 13.9,
              "temp_f": 57,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 8.5,
              "wind_kph": 13.7,
              "wind_degree": 244,
              "wind_dir": "WSW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 88,
              "cloud": 52,
              "feelslike_c": 12.9,
              "feelslike_f": 55.2,
              "windchill_c": 12.9,
              "windchill_f": 55.2,
              "heatindex_c": 13.9,
              "heatindex_f": 57,
              "dewpoint_c": 11.9,
              "dewpoint_f": 53.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.4,
              "gust_kph": 18.4,
              "uv": 4
            },
            {
              "time_epoch": 1689138000,
              "time": "2023-07-12 06:00",
              "temp_c": 14.8,
              "temp_f": 58.6,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 249,
              "wind_dir": "WSW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 82,
              "cloud": 35,
              "feelslike_c": 13.8,
              "feelslike_f": 56.8,
              "windchill_c": 13.8,
              "windchill_f": 56.8,
              "heatindex_c": 14.8,
              "heatindex_f": 58.6,
              "dewpoint_c": 11.7,
              "dewpoint_f": 53.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.9,
              "gust_kph": 19.1,
              "uv": 4
            },
            {
              "time_epoch": 1689141600,
              "time": "2023-07-12 07:00",
              "temp_c": 16.4,
              "temp_f": 61.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 255,
              "wind_dir": "WSW",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 72,
              "cloud": 43,
              "feelslike_c": 16.4,
              "feelslike_f": 61.5,
              "windchill_c": 16.4,
              "windchill_f": 61.5,
              "heatindex_c": 16.4,
              "heatindex_f": 61.5,
              "dewpoint_c": 11.3,
              "dewpoint_f": 52.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.1,
              "gust_kph": 19.4,
              "uv": 5
            },
            {
              "time_epoch": 1689145200,
              "time": "2023-07-12 08:00",
              "temp_c": 17.8,
              "temp_f": 64,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 259,
              "wind_dir": "W",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 62,
              "cloud": 20,
              "feelslike_c": 17.8,
              "feelslike_f": 64,
              "windchill_c": 17.8,
              "windchill_f": 64,
              "heatindex_c": 17.8,
              "heatindex_f": 64,
              "dewpoint_c": 10.3,
              "dewpoint_f": 50.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.4,
              "gust_kph": 21.6,
              "uv": 5
            },
            {
              "time_epoch": 1689148800,
              "time": "2023-07-12 09:00",
              "temp_c": 19.3,
              "temp_f": 66.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 12.3,
              "wind_kph": 19.8,
              "wind_degree": 261,
              "wind_dir": "W",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 52,
              "cloud": 19,
              "feelslike_c": 19.3,
              "feelslike_f": 66.7,
              "windchill_c": 19.3,
              "windchill_f": 66.7,
              "heatindex_c": 19.3,
              "heatindex_f": 66.7,
              "dewpoint_c": 9.2,
              "dewpoint_f": 48.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 5
            },
            {
              "time_epoch": 1689152400,
              "time": "2023-07-12 10:00",
              "temp_c": 20.6,
              "temp_f": 69.1,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 258,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 46,
              "cloud": 39,
              "feelslike_c": 20.6,
              "feelslike_f": 69.1,
              "windchill_c": 20.6,
              "windchill_f": 69.1,
              "heatindex_c": 20.6,
              "heatindex_f": 69.1,
              "dewpoint_c": 8.7,
              "dewpoint_f": 47.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.8,
              "gust_kph": 23.8,
              "uv": 6
            },
            {
              "time_epoch": 1689156000,
              "time": "2023-07-12 11:00",
              "temp_c": 21.8,
              "temp_f": 71.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 13.4,
              "wind_kph": 21.6,
              "wind_degree": 249,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 42,
              "cloud": 38,
              "feelslike_c": 21.8,
              "feelslike_f": 71.2,
              "windchill_c": 21.8,
              "windchill_f": 71.2,
              "heatindex_c": 24.1,
              "heatindex_f": 75.4,
              "dewpoint_c": 8.4,
              "dewpoint_f": 47.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.4,
              "gust_kph": 24.8,
              "uv": 6
            },
            {
              "time_epoch": 1689159600,
              "time": "2023-07-12 12:00",
              "temp_c": 21,
              "temp_f": 69.8,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 15.2,
              "wind_kph": 24.5,
              "wind_degree": 249,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 50,
              "cloud": 82,
              "feelslike_c": 21,
              "feelslike_f": 69.8,
              "windchill_c": 21,
              "windchill_f": 69.8,
              "heatindex_c": 21,
              "heatindex_f": 69.8,
              "dewpoint_c": 10.2,
              "dewpoint_f": 50.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.4,
              "gust_kph": 28.1,
              "uv": 5
            },
            {
              "time_epoch": 1689163200,
              "time": "2023-07-12 13:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11.2,
              "wind_kph": 18,
              "wind_degree": 241,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "humidity": 73,
              "cloud": 82,
              "feelslike_c": 17.9,
              "feelslike_f": 64.2,
              "windchill_c": 17.9,
              "windchill_f": 64.2,
              "heatindex_c": 17.9,
              "heatindex_f": 64.2,
              "dewpoint_c": 12.9,
              "dewpoint_f": 55.2,
              "will_it_rain": 1,
              "chance_of_rain": 77,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 14.8,
              "gust_kph": 23.8,
              "uv": 4
            },
            {
              "time_epoch": 1689166800,
              "time": "2023-07-12 14:00",
              "temp_c": 19.3,
              "temp_f": 66.7,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 12.3,
              "wind_kph": 19.8,
              "wind_degree": 237,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "humidity": 66,
              "cloud": 91,
              "feelslike_c": 19.3,
              "feelslike_f": 66.7,
              "windchill_c": 19.3,
              "windchill_f": 66.7,
              "heatindex_c": 19.3,
              "heatindex_f": 66.7,
              "dewpoint_c": 12.8,
              "dewpoint_f": 55,
              "will_it_rain": 1,
              "chance_of_rain": 86,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.1,
              "gust_kph": 25.9,
              "uv": 4
            },
            {
              "time_epoch": 1689170400,
              "time": "2023-07-12 15:00",
              "temp_c": 19.8,
              "temp_f": 67.6,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 13.2,
              "wind_kph": 21.2,
              "wind_degree": 242,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 1.6,
              "precip_in": 0.06,
              "humidity": 64,
              "cloud": 83,
              "feelslike_c": 19.8,
              "feelslike_f": 67.6,
              "windchill_c": 19.8,
              "windchill_f": 67.6,
              "heatindex_c": 19.8,
              "heatindex_f": 67.6,
              "dewpoint_c": 12.8,
              "dewpoint_f": 55,
              "will_it_rain": 1,
              "chance_of_rain": 81,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.8,
              "gust_kph": 30.2,
              "uv": 4
            },
            {
              "time_epoch": 1689174000,
              "time": "2023-07-12 16:00",
              "temp_c": 20.1,
              "temp_f": 68.2,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 13,
              "wind_kph": 20.9,
              "wind_degree": 252,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "humidity": 62,
              "cloud": 77,
              "feelslike_c": 20.1,
              "feelslike_f": 68.2,
              "windchill_c": 20.1,
              "windchill_f": 68.2,
              "heatindex_c": 20.1,
              "heatindex_f": 68.2,
              "dewpoint_c": 12.6,
              "dewpoint_f": 54.7,
              "will_it_rain": 1,
              "chance_of_rain": 82,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 19,
              "gust_kph": 30.6,
              "uv": 5
            },
            {
              "time_epoch": 1689177600,
              "time": "2023-07-12 17:00",
              "temp_c": 20.4,
              "temp_f": 68.7,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 250,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "humidity": 61,
              "cloud": 76,
              "feelslike_c": 20.4,
              "feelslike_f": 68.7,
              "windchill_c": 20.4,
              "windchill_f": 68.7,
              "heatindex_c": 20.4,
              "heatindex_f": 68.7,
              "dewpoint_c": 12.7,
              "dewpoint_f": 54.9,
              "will_it_rain": 0,
              "chance_of_rain": 63,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9,
              "vis_miles": 5,
              "gust_mph": 18.3,
              "gust_kph": 29.5,
              "uv": 5
            },
            {
              "time_epoch": 1689181200,
              "time": "2023-07-12 18:00",
              "temp_c": 20.7,
              "temp_f": 69.3,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 258,
              "wind_dir": "WSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 2.4,
              "precip_in": 0.09,
              "humidity": 58,
              "cloud": 51,
              "feelslike_c": 20.7,
              "feelslike_f": 69.3,
              "windchill_c": 20.7,
              "windchill_f": 69.3,
              "heatindex_c": 20.7,
              "heatindex_f": 69.3,
              "dewpoint_c": 12.2,
              "dewpoint_f": 54,
              "will_it_rain": 1,
              "chance_of_rain": 82,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.3,
              "gust_kph": 26.3,
              "uv": 5
            },
            {
              "time_epoch": 1689184800,
              "time": "2023-07-12 19:00",
              "temp_c": 19.9,
              "temp_f": 67.8,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.3,
              "wind_kph": 16.6,
              "wind_degree": 264,
              "wind_dir": "W",
              "pressure_mb": 1011,
              "pressure_in": 29.87,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 60,
              "cloud": 42,
              "feelslike_c": 19.9,
              "feelslike_f": 67.8,
              "windchill_c": 19.9,
              "windchill_f": 67.8,
              "heatindex_c": 19.9,
              "heatindex_f": 67.8,
              "dewpoint_c": 12,
              "dewpoint_f": 53.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.5,
              "gust_kph": 20.2,
              "uv": 5
            },
            {
              "time_epoch": 1689188400,
              "time": "2023-07-12 20:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 260,
              "wind_dir": "W",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 67,
              "cloud": 37,
              "feelslike_c": 17.9,
              "feelslike_f": 64.2,
              "windchill_c": 17.9,
              "windchill_f": 64.2,
              "heatindex_c": 17.9,
              "heatindex_f": 64.2,
              "dewpoint_c": 11.7,
              "dewpoint_f": 53.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15,
              "gust_kph": 24.1,
              "uv": 5
            },
            {
              "time_epoch": 1689192000,
              "time": "2023-07-12 21:00",
              "temp_c": 17,
              "temp_f": 62.6,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 257,
              "wind_dir": "WSW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 72,
              "cloud": 27,
              "feelslike_c": 17,
              "feelslike_f": 62.6,
              "windchill_c": 17,
              "windchill_f": 62.6,
              "heatindex_c": 17,
              "heatindex_f": 62.6,
              "dewpoint_c": 11.9,
              "dewpoint_f": 53.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 5
            },
            {
              "time_epoch": 1689195600,
              "time": "2023-07-12 22:00",
              "temp_c": 16.3,
              "temp_f": 61.3,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 254,
              "wind_dir": "WSW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 75,
              "cloud": 37,
              "feelslike_c": 16.3,
              "feelslike_f": 61.3,
              "windchill_c": 16.3,
              "windchill_f": 61.3,
              "heatindex_c": 16.3,
              "heatindex_f": 61.3,
              "dewpoint_c": 11.9,
              "dewpoint_f": 53.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.2,
              "gust_kph": 21.2,
              "uv": 1
            },
            {
              "time_epoch": 1689199200,
              "time": "2023-07-12 23:00",
              "temp_c": 15.6,
              "temp_f": 60.1,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 259,
              "wind_dir": "W",
              "pressure_mb": 1014,
              "pressure_in": 29.93,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 79,
              "cloud": 19,
              "feelslike_c": 15.6,
              "feelslike_f": 60.1,
              "windchill_c": 15.6,
              "windchill_f": 60.1,
              "heatindex_c": 15.6,
              "heatindex_f": 60.1,
              "dewpoint_c": 11.9,
              "dewpoint_f": 53.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.3,
              "gust_kph": 19.8,
              "uv": 1
            }
          ]
        }
      ]
    }
}

export const forecastWeatherSlice = createSlice({
    name: 'forecastWeatherSlice',
    initialState,
    reducers: {},
    extraReducers: (builder) => {
        builder.addCase(setForecastWeatherAsync.fulfilled, (_: IForecastWeather, { payload }: PayloadAction<IForecastWeather>): IForecastWeather => {
            return payload;
        });
    },
});

export const setForecastWeatherAsync = createAsyncThunk("forecastWeather/setForecastWeather", async (payload: IForecastWeather): Promise<IForecastWeather> => {
	return payload;
});

export default forecastWeatherSlice.reducer;