import { IForecast } from '../types';
import type { PayloadAction } from '@reduxjs/toolkit';
import { ILocation, ICurrentWeather } from '../types';
import { flashMessage } from '../../controllers/flashMessage';
import { MessagesTypes } from '../../constants/messagesTypes';
import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { forecastWeatherAPI } from '../../controllers/api/forecastWeather';
import { FlashMessageBackgroundColors, FlashMessageColors } from '../../constants/themes';

interface IForecastWeatherData {
  location: ILocation;
  forecast: IForecast;
  current: ICurrentWeather;
}

export interface IForecastWeather {
  error: boolean;
  loading: boolean;
  data: IForecastWeatherData;
};

const initialState: IForecastWeather = {
  data: {
    "location": {
      "name": "Kiev",
      "region": "Kyyivs'ka Oblast'",
      "country": "Ukraine",
      "lat": 50.43,
      "lon": 30.52,
      "tz_id": "Europe/Kiev",
      "localtime_epoch": 1689157243,
      "localtime": "2023-07-12 13:20"
    },
    "current": {
      "last_updated_epoch": 1689156900,
      "last_updated": "2023-07-12 13:15",
      "temp_c": 24.3,
      "temp_f": 75.7,
      "is_day": 1,
      "condition": {
        "text": "Sunny",
        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
        "code": 1000
      },
      "wind_mph": 6.5,
      "wind_kph": 10.4,
      "wind_degree": 285,
      "wind_dir": "WNW",
      "pressure_mb": 1015,
      "pressure_in": 29.98,
      "precip_mm": 0,
      "precip_in": 0,
      "humidity": 30,
      "cloud": 17,
      "feelslike_c": 24.3,
      "feelslike_f": 75.7,
      "vis_km": 10,
      "vis_miles": 6,
      "uv": 6,
      "gust_mph": 7.4,
      "gust_kph": 11.9
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2023-07-12",
          "date_epoch": 1689120000,
          "day": {
            "maxtemp_c": 25.4,
            "maxtemp_f": 77.7,
            "mintemp_c": 14,
            "mintemp_f": 57.2,
            "avgtemp_c": 19.8,
            "avgtemp_f": 67.6,
            "maxwind_mph": 6.5,
            "maxwind_kph": 10.4,
            "totalprecip_mm": 0,
            "totalprecip_in": 0,
            "totalsnow_cm": 0,
            "avgvis_km": 10,
            "avgvis_miles": 6,
            "avghumidity": 49,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 0,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "uv": 5
          },
          "astro": {
            "sunrise": "05:00 AM",
            "sunset": "09:07 PM",
            "moonrise": "12:54 AM",
            "moonset": "04:28 PM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": "30",
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1689109200,
              "time": "2023-07-12 00:00",
              "temp_c": 16,
              "temp_f": 60.8,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 354,
              "wind_dir": "N",
              "pressure_mb": 1015,
              "pressure_in": 29.98,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 68,
              "cloud": 21,
              "feelslike_c": 16,
              "feelslike_f": 60.8,
              "windchill_c": 16,
              "windchill_f": 60.8,
              "heatindex_c": 16,
              "heatindex_f": 60.8,
              "dewpoint_c": 10,
              "dewpoint_f": 50,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6,
              "gust_kph": 9.7,
              "uv": 1
            },
            {
              "time_epoch": 1689112800,
              "time": "2023-07-12 01:00",
              "temp_c": 15.9,
              "temp_f": 60.6,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 344,
              "wind_dir": "NNW",
              "pressure_mb": 1016,
              "pressure_in": 29.99,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 68,
              "cloud": 22,
              "feelslike_c": 15.9,
              "feelslike_f": 60.6,
              "windchill_c": 15.9,
              "windchill_f": 60.6,
              "heatindex_c": 15.9,
              "heatindex_f": 60.6,
              "dewpoint_c": 10,
              "dewpoint_f": 50,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6,
              "gust_kph": 9.7,
              "uv": 1
            },
            {
              "time_epoch": 1689116400,
              "time": "2023-07-12 02:00",
              "temp_c": 15.6,
              "temp_f": 60.1,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 339,
              "wind_dir": "NNW",
              "pressure_mb": 1016,
              "pressure_in": 29.99,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 68,
              "cloud": 22,
              "feelslike_c": 15.6,
              "feelslike_f": 60.1,
              "windchill_c": 15.6,
              "windchill_f": 60.1,
              "heatindex_c": 15.6,
              "heatindex_f": 60.1,
              "dewpoint_c": 9.7,
              "dewpoint_f": 49.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6,
              "gust_kph": 9.7,
              "uv": 1
            },
            {
              "time_epoch": 1689120000,
              "time": "2023-07-12 03:00",
              "temp_c": 14.1,
              "temp_f": 57.4,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4,
              "wind_kph": 6.5,
              "wind_degree": 339,
              "wind_dir": "NNW",
              "pressure_mb": 1016,
              "pressure_in": 29.99,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 74,
              "cloud": 32,
              "feelslike_c": 14.1,
              "feelslike_f": 57.4,
              "windchill_c": 14.1,
              "windchill_f": 57.4,
              "heatindex_c": 14.1,
              "heatindex_f": 57.4,
              "dewpoint_c": 9.4,
              "dewpoint_f": 48.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.6,
              "gust_kph": 12.2,
              "uv": 1
            },
            {
              "time_epoch": 1689123600,
              "time": "2023-07-12 04:00",
              "temp_c": 14,
              "temp_f": 57.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 342,
              "wind_dir": "NNW",
              "pressure_mb": 1016,
              "pressure_in": 30,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 73,
              "cloud": 46,
              "feelslike_c": 13.9,
              "feelslike_f": 57,
              "windchill_c": 13.9,
              "windchill_f": 57,
              "heatindex_c": 14,
              "heatindex_f": 57.2,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.6,
              "gust_kph": 12.2,
              "uv": 1
            },
            {
              "time_epoch": 1689127200,
              "time": "2023-07-12 05:00",
              "temp_c": 14.4,
              "temp_f": 57.9,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 349,
              "wind_dir": "N",
              "pressure_mb": 1016,
              "pressure_in": 30.01,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 70,
              "cloud": 32,
              "feelslike_c": 14.5,
              "feelslike_f": 58.1,
              "windchill_c": 14.5,
              "windchill_f": 58.1,
              "heatindex_c": 14.4,
              "heatindex_f": 57.9,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6,
              "gust_kph": 9.7,
              "uv": 1
            },
            {
              "time_epoch": 1689130800,
              "time": "2023-07-12 06:00",
              "temp_c": 15.3,
              "temp_f": 59.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 342,
              "wind_dir": "NNW",
              "pressure_mb": 1016,
              "pressure_in": 30.01,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 67,
              "cloud": 26,
              "feelslike_c": 15.3,
              "feelslike_f": 59.5,
              "windchill_c": 15.3,
              "windchill_f": 59.5,
              "heatindex_c": 15.3,
              "heatindex_f": 59.5,
              "dewpoint_c": 9.2,
              "dewpoint_f": 48.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.1,
              "gust_kph": 8.3,
              "uv": 5
            },
            {
              "time_epoch": 1689134400,
              "time": "2023-07-12 07:00",
              "temp_c": 16.7,
              "temp_f": 62.1,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 334,
              "wind_dir": "NNW",
              "pressure_mb": 1017,
              "pressure_in": 30.02,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 60,
              "cloud": 20,
              "feelslike_c": 16.7,
              "feelslike_f": 62.1,
              "windchill_c": 16.7,
              "windchill_f": 62.1,
              "heatindex_c": 16.7,
              "heatindex_f": 62.1,
              "dewpoint_c": 9,
              "dewpoint_f": 48.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.5,
              "gust_kph": 7.2,
              "uv": 5
            },
            {
              "time_epoch": 1689138000,
              "time": "2023-07-12 08:00",
              "temp_c": 18.3,
              "temp_f": 64.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 329,
              "wind_dir": "NNW",
              "pressure_mb": 1016,
              "pressure_in": 30.01,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 52,
              "cloud": 16,
              "feelslike_c": 18.3,
              "feelslike_f": 64.9,
              "windchill_c": 18.3,
              "windchill_f": 64.9,
              "heatindex_c": 18.3,
              "heatindex_f": 64.9,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.6,
              "gust_kph": 5.8,
              "uv": 5
            },
            {
              "time_epoch": 1689141600,
              "time": "2023-07-12 09:00",
              "temp_c": 20.2,
              "temp_f": 68.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 304,
              "wind_dir": "NW",
              "pressure_mb": 1016,
              "pressure_in": 30,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 43,
              "cloud": 15,
              "feelslike_c": 20.2,
              "feelslike_f": 68.4,
              "windchill_c": 20.2,
              "windchill_f": 68.4,
              "heatindex_c": 20.2,
              "heatindex_f": 68.4,
              "dewpoint_c": 7.3,
              "dewpoint_f": 45.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.5,
              "gust_kph": 4,
              "uv": 6
            },
            {
              "time_epoch": 1689145200,
              "time": "2023-07-12 10:00",
              "temp_c": 21.4,
              "temp_f": 70.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 301,
              "wind_dir": "WNW",
              "pressure_mb": 1016,
              "pressure_in": 30,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 37,
              "cloud": 46,
              "feelslike_c": 21.4,
              "feelslike_f": 70.5,
              "windchill_c": 21.4,
              "windchill_f": 70.5,
              "heatindex_c": 23.7,
              "heatindex_f": 74.7,
              "dewpoint_c": 6,
              "dewpoint_f": 42.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4,
              "gust_kph": 6.5,
              "uv": 6
            },
            {
              "time_epoch": 1689148800,
              "time": "2023-07-12 11:00",
              "temp_c": 22.8,
              "temp_f": 73,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 4,
              "wind_kph": 6.5,
              "wind_degree": 297,
              "wind_dir": "WNW",
              "pressure_mb": 1016,
              "pressure_in": 30,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 33,
              "cloud": 30,
              "feelslike_c": 23.9,
              "feelslike_f": 75,
              "windchill_c": 22.8,
              "windchill_f": 73,
              "heatindex_c": 23.9,
              "heatindex_f": 75,
              "dewpoint_c": 5.9,
              "dewpoint_f": 42.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.7,
              "gust_kph": 7.6,
              "uv": 6
            },
            {
              "time_epoch": 1689152400,
              "time": "2023-07-12 12:00",
              "temp_c": 23.7,
              "temp_f": 74.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 293,
              "wind_dir": "WNW",
              "pressure_mb": 1015,
              "pressure_in": 29.98,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 32,
              "cloud": 22,
              "feelslike_c": 24.1,
              "feelslike_f": 75.4,
              "windchill_c": 23.7,
              "windchill_f": 74.7,
              "heatindex_c": 24.1,
              "heatindex_f": 75.4,
              "dewpoint_c": 5.9,
              "dewpoint_f": 42.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.4,
              "gust_kph": 8.6,
              "uv": 6
            },
            {
              "time_epoch": 1689156000,
              "time": "2023-07-12 13:00",
              "temp_c": 24.3,
              "temp_f": 75.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 285,
              "wind_dir": "WNW",
              "pressure_mb": 1015,
              "pressure_in": 29.98,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 30,
              "cloud": 17,
              "feelslike_c": 24.3,
              "feelslike_f": 75.7,
              "windchill_c": 24.3,
              "windchill_f": 75.7,
              "heatindex_c": 24.3,
              "heatindex_f": 75.7,
              "dewpoint_c": 5.9,
              "dewpoint_f": 42.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.4,
              "gust_kph": 11.9,
              "uv": 6
            },
            {
              "time_epoch": 1689159600,
              "time": "2023-07-12 14:00",
              "temp_c": 24.9,
              "temp_f": 76.8,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 286,
              "wind_dir": "WNW",
              "pressure_mb": 1015,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 30,
              "cloud": 14,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 24.9,
              "windchill_f": 76.8,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 6,
              "dewpoint_f": 42.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.4,
              "gust_kph": 11.9,
              "uv": 6
            },
            {
              "time_epoch": 1689163200,
              "time": "2023-07-12 15:00",
              "temp_c": 25.4,
              "temp_f": 77.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.5,
              "wind_kph": 10.4,
              "wind_degree": 290,
              "wind_dir": "WNW",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 29,
              "cloud": 13,
              "feelslike_c": 24.9,
              "feelslike_f": 76.8,
              "windchill_c": 25.4,
              "windchill_f": 77.7,
              "heatindex_c": 24.9,
              "heatindex_f": 76.8,
              "dewpoint_c": 6.2,
              "dewpoint_f": 43.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.4,
              "gust_kph": 11.9,
              "uv": 7
            },
            {
              "time_epoch": 1689166800,
              "time": "2023-07-12 16:00",
              "temp_c": 25.4,
              "temp_f": 77.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 6.3,
              "wind_kph": 10.1,
              "wind_degree": 306,
              "wind_dir": "NW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 30,
              "cloud": 14,
              "feelslike_c": 25,
              "feelslike_f": 77,
              "windchill_c": 25.4,
              "windchill_f": 77.7,
              "heatindex_c": 25,
              "heatindex_f": 77,
              "dewpoint_c": 6.7,
              "dewpoint_f": 44.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.2,
              "gust_kph": 11.5,
              "uv": 7
            },
            {
              "time_epoch": 1689170400,
              "time": "2023-07-12 17:00",
              "temp_c": 24.7,
              "temp_f": 76.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 338,
              "wind_dir": "NNW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 34,
              "cloud": 14,
              "feelslike_c": 24.8,
              "feelslike_f": 76.6,
              "windchill_c": 24.7,
              "windchill_f": 76.5,
              "heatindex_c": 24.8,
              "heatindex_f": 76.6,
              "dewpoint_c": 7.6,
              "dewpoint_f": 45.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.8,
              "gust_kph": 9.4,
              "uv": 6
            },
            {
              "time_epoch": 1689174000,
              "time": "2023-07-12 18:00",
              "temp_c": 24.4,
              "temp_f": 75.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 354,
              "wind_dir": "N",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 37,
              "cloud": 14,
              "feelslike_c": 24.8,
              "feelslike_f": 76.6,
              "windchill_c": 24.4,
              "windchill_f": 75.9,
              "heatindex_c": 24.8,
              "heatindex_f": 76.6,
              "dewpoint_c": 8.8,
              "dewpoint_f": 47.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.9,
              "gust_kph": 4.7,
              "uv": 6
            },
            {
              "time_epoch": 1689177600,
              "time": "2023-07-12 19:00",
              "temp_c": 23.3,
              "temp_f": 73.9,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 0.4,
              "wind_kph": 0.7,
              "wind_degree": 91,
              "wind_dir": "E",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 41,
              "cloud": 16,
              "feelslike_c": 24.5,
              "feelslike_f": 76.1,
              "windchill_c": 23.3,
              "windchill_f": 73.9,
              "heatindex_c": 24.5,
              "heatindex_f": 76.1,
              "dewpoint_c": 9.4,
              "dewpoint_f": 48.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 0.4,
              "gust_kph": 0.7,
              "uv": 6
            },
            {
              "time_epoch": 1689181200,
              "time": "2023-07-12 20:00",
              "temp_c": 19.6,
              "temp_f": 67.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 2.5,
              "wind_kph": 4,
              "wind_degree": 128,
              "wind_dir": "SE",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 47,
              "cloud": 17,
              "feelslike_c": 19.6,
              "feelslike_f": 67.3,
              "windchill_c": 19.6,
              "windchill_f": 67.3,
              "heatindex_c": 19.6,
              "heatindex_f": 67.3,
              "dewpoint_c": 8.1,
              "dewpoint_f": 46.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.5,
              "gust_kph": 7.2,
              "uv": 5
            },
            {
              "time_epoch": 1689184800,
              "time": "2023-07-12 21:00",
              "temp_c": 18.5,
              "temp_f": 65.3,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 156,
              "wind_dir": "SSE",
              "pressure_mb": 1015,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 51,
              "cloud": 16,
              "feelslike_c": 18.5,
              "feelslike_f": 65.3,
              "windchill_c": 18.5,
              "windchill_f": 65.3,
              "heatindex_c": 18.5,
              "heatindex_f": 65.3,
              "dewpoint_c": 8.1,
              "dewpoint_f": 46.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.3,
              "gust_kph": 10.1,
              "uv": 5
            },
            {
              "time_epoch": 1689188400,
              "time": "2023-07-12 22:00",
              "temp_c": 17.9,
              "temp_f": 64.2,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 187,
              "wind_dir": "S",
              "pressure_mb": 1015,
              "pressure_in": 29.98,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 53,
              "cloud": 12,
              "feelslike_c": 17.9,
              "feelslike_f": 64.2,
              "windchill_c": 17.9,
              "windchill_f": 64.2,
              "heatindex_c": 17.9,
              "heatindex_f": 64.2,
              "dewpoint_c": 8.1,
              "dewpoint_f": 46.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.5,
              "gust_kph": 10.4,
              "uv": 1
            },
            {
              "time_epoch": 1689192000,
              "time": "2023-07-12 23:00",
              "temp_c": 17.4,
              "temp_f": 63.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 196,
              "wind_dir": "SSW",
              "pressure_mb": 1015,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 54,
              "cloud": 4,
              "feelslike_c": 17.4,
              "feelslike_f": 63.3,
              "windchill_c": 17.4,
              "windchill_f": 63.3,
              "heatindex_c": 17.4,
              "heatindex_f": 63.3,
              "dewpoint_c": 8,
              "dewpoint_f": 46.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.4,
              "gust_kph": 11.9,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-07-13",
          "date_epoch": 1689206400,
          "day": {
            "maxtemp_c": 31.1,
            "maxtemp_f": 88,
            "mintemp_c": 16.3,
            "mintemp_f": 61.3,
            "avgtemp_c": 22.9,
            "avgtemp_f": 73.2,
            "maxwind_mph": 11.6,
            "maxwind_kph": 18.7,
            "totalprecip_mm": 6.5,
            "totalprecip_in": 0.26,
            "totalsnow_cm": 0,
            "avgvis_km": 9.9,
            "avgvis_miles": 6,
            "avghumidity": 55,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 72,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 5
          },
          "astro": {
            "sunrise": "05:01 AM",
            "sunset": "09:06 PM",
            "moonrise": "01:15 AM",
            "moonset": "05:45 PM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": "21",
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1689195600,
              "time": "2023-07-13 00:00",
              "temp_c": 16.9,
              "temp_f": 62.4,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 1015,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 55,
              "cloud": 4,
              "feelslike_c": 16.9,
              "feelslike_f": 62.4,
              "windchill_c": 16.9,
              "windchill_f": 62.4,
              "heatindex_c": 16.9,
              "heatindex_f": 62.4,
              "dewpoint_c": 7.9,
              "dewpoint_f": 46.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.7,
              "gust_kph": 14,
              "uv": 1
            },
            {
              "time_epoch": 1689199200,
              "time": "2023-07-13 01:00",
              "temp_c": 16.6,
              "temp_f": 61.9,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 227,
              "wind_dir": "SW",
              "pressure_mb": 1015,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 58,
              "cloud": 20,
              "feelslike_c": 16.6,
              "feelslike_f": 61.9,
              "windchill_c": 16.6,
              "windchill_f": 61.9,
              "heatindex_c": 16.6,
              "heatindex_f": 61.9,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.4,
              "gust_kph": 15.1,
              "uv": 1
            },
            {
              "time_epoch": 1689202800,
              "time": "2023-07-13 02:00",
              "temp_c": 16.4,
              "temp_f": 61.5,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1015,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 60,
              "cloud": 45,
              "feelslike_c": 16.4,
              "feelslike_f": 61.5,
              "windchill_c": 16.4,
              "windchill_f": 61.5,
              "heatindex_c": 16.4,
              "heatindex_f": 61.5,
              "dewpoint_c": 8.7,
              "dewpoint_f": 47.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.8,
              "gust_kph": 12.6,
              "uv": 1
            },
            {
              "time_epoch": 1689206400,
              "time": "2023-07-13 03:00",
              "temp_c": 16.3,
              "temp_f": 61.3,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.96,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 60,
              "cloud": 48,
              "feelslike_c": 16.3,
              "feelslike_f": 61.3,
              "windchill_c": 16.3,
              "windchill_f": 61.3,
              "heatindex_c": 16.3,
              "heatindex_f": 61.3,
              "dewpoint_c": 8.6,
              "dewpoint_f": 47.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.1,
              "gust_kph": 16.2,
              "uv": 1
            },
            {
              "time_epoch": 1689210000,
              "time": "2023-07-13 04:00",
              "temp_c": 16.5,
              "temp_f": 61.7,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4,
              "wind_kph": 6.5,
              "wind_degree": 218,
              "wind_dir": "SW",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 60,
              "cloud": 45,
              "feelslike_c": 16.5,
              "feelslike_f": 61.7,
              "windchill_c": 16.5,
              "windchill_f": 61.7,
              "heatindex_c": 16.5,
              "heatindex_f": 61.7,
              "dewpoint_c": 8.7,
              "dewpoint_f": 47.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.8,
              "gust_kph": 12.6,
              "uv": 1
            },
            {
              "time_epoch": 1689213600,
              "time": "2023-07-13 05:00",
              "temp_c": 16.9,
              "temp_f": 62.4,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 213,
              "wind_dir": "SSW",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 59,
              "cloud": 45,
              "feelslike_c": 16.9,
              "feelslike_f": 62.4,
              "windchill_c": 16.9,
              "windchill_f": 62.4,
              "heatindex_c": 16.9,
              "heatindex_f": 62.4,
              "dewpoint_c": 9,
              "dewpoint_f": 48.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.7,
              "gust_kph": 10.8,
              "uv": 1
            },
            {
              "time_epoch": 1689217200,
              "time": "2023-07-13 06:00",
              "temp_c": 17.6,
              "temp_f": 63.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 189,
              "wind_dir": "S",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 58,
              "cloud": 34,
              "feelslike_c": 17.6,
              "feelslike_f": 63.7,
              "windchill_c": 17.6,
              "windchill_f": 63.7,
              "heatindex_c": 17.6,
              "heatindex_f": 63.7,
              "dewpoint_c": 9.1,
              "dewpoint_f": 48.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.2,
              "gust_kph": 11.5,
              "uv": 5
            },
            {
              "time_epoch": 1689220800,
              "time": "2023-07-13 07:00",
              "temp_c": 18.7,
              "temp_f": 65.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 192,
              "wind_dir": "SSW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 55,
              "cloud": 30,
              "feelslike_c": 18.7,
              "feelslike_f": 65.7,
              "windchill_c": 18.7,
              "windchill_f": 65.7,
              "heatindex_c": 18.7,
              "heatindex_f": 65.7,
              "dewpoint_c": 9.6,
              "dewpoint_f": 49.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.3,
              "gust_kph": 10.1,
              "uv": 5
            },
            {
              "time_epoch": 1689224400,
              "time": "2023-07-13 08:00",
              "temp_c": 19.3,
              "temp_f": 66.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 190,
              "wind_dir": "S",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 55,
              "cloud": 48,
              "feelslike_c": 19.3,
              "feelslike_f": 66.7,
              "windchill_c": 19.3,
              "windchill_f": 66.7,
              "heatindex_c": 19.3,
              "heatindex_f": 66.7,
              "dewpoint_c": 10.1,
              "dewpoint_f": 50.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.3,
              "gust_kph": 10.1,
              "uv": 5
            },
            {
              "time_epoch": 1689228000,
              "time": "2023-07-13 09:00",
              "temp_c": 22,
              "temp_f": 71.6,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 177,
              "wind_dir": "S",
              "pressure_mb": 1014,
              "pressure_in": 29.93,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 48,
              "cloud": 44,
              "feelslike_c": 24.4,
              "feelslike_f": 75.9,
              "windchill_c": 22,
              "windchill_f": 71.6,
              "heatindex_c": 24.4,
              "heatindex_f": 75.9,
              "dewpoint_c": 10.6,
              "dewpoint_f": 51.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.4,
              "gust_kph": 8.6,
              "uv": 6
            },
            {
              "time_epoch": 1689231600,
              "time": "2023-07-13 10:00",
              "temp_c": 24,
              "temp_f": 75.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 5.8,
              "wind_kph": 9.4,
              "wind_degree": 170,
              "wind_dir": "S",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 44,
              "cloud": 47,
              "feelslike_c": 25,
              "feelslike_f": 77,
              "windchill_c": 24,
              "windchill_f": 75.2,
              "heatindex_c": 25,
              "heatindex_f": 77,
              "dewpoint_c": 11.1,
              "dewpoint_f": 52,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.7,
              "gust_kph": 10.8,
              "uv": 6
            },
            {
              "time_epoch": 1689235200,
              "time": "2023-07-13 11:00",
              "temp_c": 27.9,
              "temp_f": 82.2,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 177,
              "wind_dir": "S",
              "pressure_mb": 1013,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 39,
              "cloud": 46,
              "feelslike_c": 27.7,
              "feelslike_f": 81.9,
              "windchill_c": 27.9,
              "windchill_f": 82.2,
              "heatindex_c": 27.7,
              "heatindex_f": 81.9,
              "dewpoint_c": 12.8,
              "dewpoint_f": 55,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.3,
              "gust_kph": 13.3,
              "uv": 7
            },
            {
              "time_epoch": 1689238800,
              "time": "2023-07-13 12:00",
              "temp_c": 29.2,
              "temp_f": 84.6,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 8.3,
              "wind_kph": 13.3,
              "wind_degree": 200,
              "wind_dir": "SSW",
              "pressure_mb": 1013,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 37,
              "cloud": 45,
              "feelslike_c": 28.9,
              "feelslike_f": 84,
              "windchill_c": 29.2,
              "windchill_f": 84.6,
              "heatindex_c": 28.9,
              "heatindex_f": 84,
              "dewpoint_c": 13.2,
              "dewpoint_f": 55.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.6,
              "gust_kph": 15.5,
              "uv": 7
            },
            {
              "time_epoch": 1689242400,
              "time": "2023-07-13 13:00",
              "temp_c": 30,
              "temp_f": 86,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 8.5,
              "wind_kph": 13.7,
              "wind_degree": 199,
              "wind_dir": "SSW",
              "pressure_mb": 1011,
              "pressure_in": 29.87,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 37,
              "cloud": 45,
              "feelslike_c": 29.8,
              "feelslike_f": 85.6,
              "windchill_c": 30,
              "windchill_f": 86,
              "heatindex_c": 29.8,
              "heatindex_f": 85.6,
              "dewpoint_c": 13.9,
              "dewpoint_f": 57,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.8,
              "gust_kph": 15.8,
              "uv": 8
            },
            {
              "time_epoch": 1689246000,
              "time": "2023-07-13 14:00",
              "temp_c": 30.7,
              "temp_f": 87.3,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 7.6,
              "wind_kph": 12.2,
              "wind_degree": 212,
              "wind_dir": "SSW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 38,
              "cloud": 44,
              "feelslike_c": 30.7,
              "feelslike_f": 87.3,
              "windchill_c": 30.7,
              "windchill_f": 87.3,
              "heatindex_c": 30.7,
              "heatindex_f": 87.3,
              "dewpoint_c": 14.7,
              "dewpoint_f": 58.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 8.7,
              "gust_kph": 14,
              "uv": 8
            },
            {
              "time_epoch": 1689249600,
              "time": "2023-07-13 15:00",
              "temp_c": 31.1,
              "temp_f": 88,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 6.3,
              "wind_kph": 10.1,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 1010,
              "pressure_in": 29.81,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 37,
              "cloud": 28,
              "feelslike_c": 31.2,
              "feelslike_f": 88.2,
              "windchill_c": 31.1,
              "windchill_f": 88,
              "heatindex_c": 31.2,
              "heatindex_f": 88.2,
              "dewpoint_c": 14.8,
              "dewpoint_f": 58.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 7.2,
              "gust_kph": 11.5,
              "uv": 8
            },
            {
              "time_epoch": 1689253200,
              "time": "2023-07-13 16:00",
              "temp_c": 30.4,
              "temp_f": 86.7,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 219,
              "wind_dir": "SW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 39,
              "cloud": 23,
              "feelslike_c": 30.6,
              "feelslike_f": 87.1,
              "windchill_c": 30.4,
              "windchill_f": 86.7,
              "heatindex_c": 30.6,
              "heatindex_f": 87.1,
              "dewpoint_c": 15.1,
              "dewpoint_f": 59.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.8,
              "gust_kph": 9.4,
              "uv": 8
            },
            {
              "time_epoch": 1689256800,
              "time": "2023-07-13 17:00",
              "temp_c": 29.3,
              "temp_f": 84.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 246,
              "wind_dir": "WSW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 43,
              "cloud": 31,
              "feelslike_c": 29.6,
              "feelslike_f": 85.3,
              "windchill_c": 29.3,
              "windchill_f": 84.7,
              "heatindex_c": 29.6,
              "heatindex_f": 85.3,
              "dewpoint_c": 15.5,
              "dewpoint_f": 59.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6,
              "gust_kph": 9.7,
              "uv": 7
            },
            {
              "time_epoch": 1689260400,
              "time": "2023-07-13 18:00",
              "temp_c": 27.1,
              "temp_f": 80.8,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 324,
              "wind_dir": "NW",
              "pressure_mb": 1009,
              "pressure_in": 29.79,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 50,
              "cloud": 36,
              "feelslike_c": 27.7,
              "feelslike_f": 81.9,
              "windchill_c": 27.1,
              "windchill_f": 80.8,
              "heatindex_c": 27.7,
              "heatindex_f": 81.9,
              "dewpoint_c": 15.9,
              "dewpoint_f": 60.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5.6,
              "gust_kph": 9,
              "uv": 7
            },
            {
              "time_epoch": 1689264000,
              "time": "2023-07-13 19:00",
              "temp_c": 25.6,
              "temp_f": 78.1,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 323,
              "wind_dir": "NW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 55,
              "cloud": 50,
              "feelslike_c": 26.5,
              "feelslike_f": 79.7,
              "windchill_c": 25.6,
              "windchill_f": 78.1,
              "heatindex_c": 26.5,
              "heatindex_f": 79.7,
              "dewpoint_c": 15.9,
              "dewpoint_f": 60.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.4,
              "gust_kph": 24.8,
              "uv": 7
            },
            {
              "time_epoch": 1689267600,
              "time": "2023-07-13 20:00",
              "temp_c": 24.6,
              "temp_f": 76.3,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 327,
              "wind_dir": "NNW",
              "pressure_mb": 1009,
              "pressure_in": 29.8,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 62,
              "cloud": 57,
              "feelslike_c": 25.9,
              "feelslike_f": 78.6,
              "windchill_c": 24.6,
              "windchill_f": 76.3,
              "heatindex_c": 25.9,
              "heatindex_f": 78.6,
              "dewpoint_c": 16.9,
              "dewpoint_f": 62.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.9,
              "gust_kph": 28.8,
              "uv": 6
            },
            {
              "time_epoch": 1689271200,
              "time": "2023-07-13 21:00",
              "temp_c": 22.1,
              "temp_f": 71.8,
              "is_day": 1,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                "code": 1240
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 313,
              "wind_dir": "NW",
              "pressure_mb": 1010,
              "pressure_in": 29.82,
              "precip_mm": 0.9,
              "precip_in": 0.04,
              "humidity": 77,
              "cloud": 69,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 22.1,
              "windchill_f": 71.8,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 17.9,
              "dewpoint_f": 64.2,
              "will_it_rain": 0,
              "chance_of_rain": 61,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 18.8,
              "gust_kph": 30.2,
              "uv": 5
            },
            {
              "time_epoch": 1689274800,
              "time": "2023-07-13 22:00",
              "temp_c": 20.5,
              "temp_f": 68.9,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 325,
              "wind_dir": "NW",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 1.4,
              "precip_in": 0.06,
              "humidity": 89,
              "cloud": 86,
              "feelslike_c": 20.5,
              "feelslike_f": 68.9,
              "windchill_c": 20.5,
              "windchill_f": 68.9,
              "heatindex_c": 20.5,
              "heatindex_f": 68.9,
              "dewpoint_c": 18.6,
              "dewpoint_f": 65.5,
              "will_it_rain": 0,
              "chance_of_rain": 61,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.3,
              "gust_kph": 23,
              "uv": 1
            },
            {
              "time_epoch": 1689278400,
              "time": "2023-07-13 23:00",
              "temp_c": 20,
              "temp_f": 68,
              "is_day": 0,
              "condition": {
                "text": "Moderate or heavy rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/356.png",
                "code": 1243
              },
              "wind_mph": 6.9,
              "wind_kph": 11.2,
              "wind_degree": 329,
              "wind_dir": "NNW",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 4.2,
              "precip_in": 0.17,
              "humidity": 91,
              "cloud": 82,
              "feelslike_c": 20,
              "feelslike_f": 68,
              "windchill_c": 20,
              "windchill_f": 68,
              "heatindex_c": 20,
              "heatindex_f": 68,
              "dewpoint_c": 18.4,
              "dewpoint_f": 65.1,
              "will_it_rain": 1,
              "chance_of_rain": 72,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 11.6,
              "gust_kph": 18.7,
              "uv": 1
            }
          ]
        },
        {
          "date": "2023-07-14",
          "date_epoch": 1689292800,
          "day": {
            "maxtemp_c": 27.8,
            "maxtemp_f": 82,
            "mintemp_c": 17.3,
            "mintemp_f": 63.1,
            "avgtemp_c": 21.7,
            "avgtemp_f": 71.1,
            "maxwind_mph": 15.2,
            "maxwind_kph": 24.5,
            "totalprecip_mm": 7.1,
            "totalprecip_in": 0.28,
            "totalsnow_cm": 0,
            "avgvis_km": 9.9,
            "avgvis_miles": 6,
            "avghumidity": 61,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 87,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 5
          },
          "astro": {
            "sunrise": "05:02 AM",
            "sunset": "09:05 PM",
            "moonrise": "01:41 AM",
            "moonset": "06:57 PM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": "13",
            "is_moon_up": 1,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1689282000,
              "time": "2023-07-14 00:00",
              "temp_c": 19.4,
              "temp_f": 66.9,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 7.4,
              "wind_kph": 11.9,
              "wind_degree": 305,
              "wind_dir": "NW",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 1.1,
              "precip_in": 0.04,
              "humidity": 91,
              "cloud": 90,
              "feelslike_c": 19.4,
              "feelslike_f": 66.9,
              "windchill_c": 19.4,
              "windchill_f": 66.9,
              "heatindex_c": 19.4,
              "heatindex_f": 66.9,
              "dewpoint_c": 17.9,
              "dewpoint_f": 64.2,
              "will_it_rain": 1,
              "chance_of_rain": 83,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.3,
              "gust_kph": 19.8,
              "uv": 1
            },
            {
              "time_epoch": 1689285600,
              "time": "2023-07-14 01:00",
              "temp_c": 19,
              "temp_f": 66.2,
              "is_day": 0,
              "condition": {
                "text": "Light rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/353.png",
                "code": 1240
              },
              "wind_mph": 8.3,
              "wind_kph": 13.3,
              "wind_degree": 303,
              "wind_dir": "WNW",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 1,
              "precip_in": 0.04,
              "humidity": 92,
              "cloud": 87,
              "feelslike_c": 19,
              "feelslike_f": 66.2,
              "windchill_c": 19,
              "windchill_f": 66.2,
              "heatindex_c": 19,
              "heatindex_f": 66.2,
              "dewpoint_c": 17.6,
              "dewpoint_f": 63.7,
              "will_it_rain": 1,
              "chance_of_rain": 74,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 1
            },
            {
              "time_epoch": 1689289200,
              "time": "2023-07-14 02:00",
              "temp_c": 18.5,
              "temp_f": 65.3,
              "is_day": 0,
              "condition": {
                "text": "Moderate or heavy rain shower",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/356.png",
                "code": 1243
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 309,
              "wind_dir": "NW",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 4.6,
              "precip_in": 0.18,
              "humidity": 93,
              "cloud": 83,
              "feelslike_c": 18.5,
              "feelslike_f": 65.3,
              "windchill_c": 18.5,
              "windchill_f": 65.3,
              "heatindex_c": 18.5,
              "heatindex_f": 65.3,
              "dewpoint_c": 17.3,
              "dewpoint_f": 63.1,
              "will_it_rain": 0,
              "chance_of_rain": 69,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7,
              "vis_miles": 4,
              "gust_mph": 15.2,
              "gust_kph": 24.5,
              "uv": 1
            },
            {
              "time_epoch": 1689292800,
              "time": "2023-07-14 03:00",
              "temp_c": 17.7,
              "temp_f": 63.9,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 306,
              "wind_dir": "NW",
              "pressure_mb": 1010,
              "pressure_in": 29.83,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 94,
              "cloud": 33,
              "feelslike_c": 17.7,
              "feelslike_f": 63.9,
              "windchill_c": 17.7,
              "windchill_f": 63.9,
              "heatindex_c": 17.7,
              "heatindex_f": 63.9,
              "dewpoint_c": 16.7,
              "dewpoint_f": 62.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 1
            },
            {
              "time_epoch": 1689296400,
              "time": "2023-07-14 04:00",
              "temp_c": 17.4,
              "temp_f": 63.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 315,
              "wind_dir": "NW",
              "pressure_mb": 1011,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 92,
              "cloud": 18,
              "feelslike_c": 17.4,
              "feelslike_f": 63.3,
              "windchill_c": 17.4,
              "windchill_f": 63.3,
              "heatindex_c": 17.4,
              "heatindex_f": 63.3,
              "dewpoint_c": 16.1,
              "dewpoint_f": 61,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 1
            },
            {
              "time_epoch": 1689300000,
              "time": "2023-07-14 05:00",
              "temp_c": 17.3,
              "temp_f": 63.1,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 8.5,
              "wind_kph": 13.7,
              "wind_degree": 315,
              "wind_dir": "NW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 88,
              "cloud": 17,
              "feelslike_c": 17.3,
              "feelslike_f": 63.1,
              "windchill_c": 17.3,
              "windchill_f": 63.1,
              "heatindex_c": 17.3,
              "heatindex_f": 63.1,
              "dewpoint_c": 15.2,
              "dewpoint_f": 59.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 1
            },
            {
              "time_epoch": 1689303600,
              "time": "2023-07-14 06:00",
              "temp_c": 18,
              "temp_f": 64.4,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 308,
              "wind_dir": "NW",
              "pressure_mb": 1012,
              "pressure_in": 29.87,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 81,
              "cloud": 36,
              "feelslike_c": 18,
              "feelslike_f": 64.4,
              "windchill_c": 18,
              "windchill_f": 64.4,
              "heatindex_c": 18,
              "heatindex_f": 64.4,
              "dewpoint_c": 14.7,
              "dewpoint_f": 58.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.4,
              "gust_kph": 21.6,
              "uv": 5
            },
            {
              "time_epoch": 1689307200,
              "time": "2023-07-14 07:00",
              "temp_c": 19.4,
              "temp_f": 66.9,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 317,
              "wind_dir": "NW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 70,
              "cloud": 47,
              "feelslike_c": 19.4,
              "feelslike_f": 66.9,
              "windchill_c": 19.4,
              "windchill_f": 66.9,
              "heatindex_c": 19.4,
              "heatindex_f": 66.9,
              "dewpoint_c": 13.8,
              "dewpoint_f": 56.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.9,
              "gust_kph": 22.3,
              "uv": 5
            },
            {
              "time_epoch": 1689310800,
              "time": "2023-07-14 08:00",
              "temp_c": 20.4,
              "temp_f": 68.7,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 323,
              "wind_dir": "NW",
              "pressure_mb": 1013,
              "pressure_in": 29.9,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 65,
              "cloud": 39,
              "feelslike_c": 20.4,
              "feelslike_f": 68.7,
              "windchill_c": 20.4,
              "windchill_f": 68.7,
              "heatindex_c": 20.4,
              "heatindex_f": 68.7,
              "dewpoint_c": 13.6,
              "dewpoint_f": 56.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.6,
              "gust_kph": 22,
              "uv": 6
            },
            {
              "time_epoch": 1689314400,
              "time": "2023-07-14 09:00",
              "temp_c": 20.9,
              "temp_f": 69.6,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 328,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 64,
              "cloud": 52,
              "feelslike_c": 20.9,
              "feelslike_f": 69.6,
              "windchill_c": 20.9,
              "windchill_f": 69.6,
              "heatindex_c": 20.9,
              "heatindex_f": 69.6,
              "dewpoint_c": 13.9,
              "dewpoint_f": 57,
              "will_it_rain": 1,
              "chance_of_rain": 76,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.3,
              "gust_kph": 23,
              "uv": 5
            },
            {
              "time_epoch": 1689318000,
              "time": "2023-07-14 10:00",
              "temp_c": 20.8,
              "temp_f": 69.4,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 10.3,
              "wind_kph": 16.6,
              "wind_degree": 333,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.91,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 60,
              "cloud": 72,
              "feelslike_c": 20.8,
              "feelslike_f": 69.4,
              "windchill_c": 20.8,
              "windchill_f": 69.4,
              "heatindex_c": 20.8,
              "heatindex_f": 69.4,
              "dewpoint_c": 12.8,
              "dewpoint_f": 55,
              "will_it_rain": 1,
              "chance_of_rain": 79,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 5
            },
            {
              "time_epoch": 1689321600,
              "time": "2023-07-14 11:00",
              "temp_c": 22.4,
              "temp_f": 72.3,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 10.3,
              "wind_kph": 16.6,
              "wind_degree": 329,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 52,
              "cloud": 78,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 22.4,
              "windchill_f": 72.3,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 12.2,
              "dewpoint_f": 54,
              "will_it_rain": 1,
              "chance_of_rain": 87,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 5
            },
            {
              "time_epoch": 1689325200,
              "time": "2023-07-14 12:00",
              "temp_c": 24.7,
              "temp_f": 76.5,
              "is_day": 1,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 12.8,
              "wind_kph": 20.5,
              "wind_degree": 335,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 41,
              "cloud": 63,
              "feelslike_c": 25.2,
              "feelslike_f": 77.4,
              "windchill_c": 24.7,
              "windchill_f": 76.5,
              "heatindex_c": 25.2,
              "heatindex_f": 77.4,
              "dewpoint_c": 10.8,
              "dewpoint_f": 51.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.7,
              "gust_kph": 25.2,
              "uv": 5
            },
            {
              "time_epoch": 1689328800,
              "time": "2023-07-14 13:00",
              "temp_c": 25.9,
              "temp_f": 78.6,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 13.9,
              "wind_kph": 22.3,
              "wind_degree": 335,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.93,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 35,
              "cloud": 42,
              "feelslike_c": 25.7,
              "feelslike_f": 78.3,
              "windchill_c": 25.9,
              "windchill_f": 78.6,
              "heatindex_c": 25.7,
              "heatindex_f": 78.3,
              "dewpoint_c": 9.3,
              "dewpoint_f": 48.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.9,
              "gust_kph": 25.6,
              "uv": 7
            },
            {
              "time_epoch": 1689332400,
              "time": "2023-07-14 14:00",
              "temp_c": 27.8,
              "temp_f": 82,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 13.2,
              "wind_kph": 21.2,
              "wind_degree": 334,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.93,
              "precip_mm": 0.1,
              "precip_in": 0,
              "humidity": 31,
              "cloud": 74,
              "feelslike_c": 26.9,
              "feelslike_f": 80.4,
              "windchill_c": 27.8,
              "windchill_f": 82,
              "heatindex_c": 26.9,
              "heatindex_f": 80.4,
              "dewpoint_c": 9.2,
              "dewpoint_f": 48.6,
              "will_it_rain": 1,
              "chance_of_rain": 82,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.2,
              "gust_kph": 24.5,
              "uv": 6
            },
            {
              "time_epoch": 1689336000,
              "time": "2023-07-14 15:00",
              "temp_c": 27.5,
              "temp_f": 81.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 14.3,
              "wind_kph": 23,
              "wind_degree": 335,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.93,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 29,
              "cloud": 9,
              "feelslike_c": 26.4,
              "feelslike_f": 79.5,
              "windchill_c": 27.5,
              "windchill_f": 81.5,
              "heatindex_c": 26.4,
              "heatindex_f": 79.5,
              "dewpoint_c": 7.8,
              "dewpoint_f": 46,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.6,
              "gust_kph": 26.6,
              "uv": 7
            },
            {
              "time_epoch": 1689339600,
              "time": "2023-07-14 16:00",
              "temp_c": 26.8,
              "temp_f": 80.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 15.2,
              "wind_kph": 24.5,
              "wind_degree": 334,
              "wind_dir": "NNW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 31,
              "cloud": 13,
              "feelslike_c": 26.1,
              "feelslike_f": 79,
              "windchill_c": 26.8,
              "windchill_f": 80.2,
              "heatindex_c": 26.1,
              "heatindex_f": 79,
              "dewpoint_c": 8.3,
              "dewpoint_f": 46.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 17.7,
              "gust_kph": 28.4,
              "uv": 7
            },
            {
              "time_epoch": 1689343200,
              "time": "2023-07-14 17:00",
              "temp_c": 26.1,
              "temp_f": 79,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 13.4,
              "wind_kph": 21.6,
              "wind_degree": 337,
              "wind_dir": "NNW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 35,
              "cloud": 19,
              "feelslike_c": 25.8,
              "feelslike_f": 78.4,
              "windchill_c": 26.1,
              "windchill_f": 79,
              "heatindex_c": 25.8,
              "heatindex_f": 78.4,
              "dewpoint_c": 9.3,
              "dewpoint_f": 48.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.8,
              "gust_kph": 27,
              "uv": 7
            },
            {
              "time_epoch": 1689346800,
              "time": "2023-07-14 18:00",
              "temp_c": 25.3,
              "temp_f": 77.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.3,
              "wind_kph": 16.6,
              "wind_degree": 341,
              "wind_dir": "NNW",
              "pressure_mb": 1014,
              "pressure_in": 29.95,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 39,
              "cloud": 29,
              "feelslike_c": 25.5,
              "feelslike_f": 77.9,
              "windchill_c": 25.3,
              "windchill_f": 77.5,
              "heatindex_c": 25.5,
              "heatindex_f": 77.9,
              "dewpoint_c": 10.4,
              "dewpoint_f": 50.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.3,
              "gust_kph": 23,
              "uv": 7
            },
            {
              "time_epoch": 1689350400,
              "time": "2023-07-14 19:00",
              "temp_c": 23.8,
              "temp_f": 74.8,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 323,
              "wind_dir": "NW",
              "pressure_mb": 1015,
              "pressure_in": 29.97,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 46,
              "cloud": 42,
              "feelslike_c": 25,
              "feelslike_f": 77,
              "windchill_c": 23.8,
              "windchill_f": 74.8,
              "heatindex_c": 25,
              "heatindex_f": 77,
              "dewpoint_c": 11.6,
              "dewpoint_f": 52.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.8,
              "gust_kph": 23.8,
              "uv": 6
            },
            {
              "time_epoch": 1689354000,
              "time": "2023-07-14 20:00",
              "temp_c": 22.5,
              "temp_f": 72.5,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 315,
              "wind_dir": "NW",
              "pressure_mb": 1016,
              "pressure_in": 29.99,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 51,
              "cloud": 30,
              "feelslike_c": 24.6,
              "feelslike_f": 76.3,
              "windchill_c": 22.5,
              "windchill_f": 72.5,
              "heatindex_c": 24.6,
              "heatindex_f": 76.3,
              "dewpoint_c": 11.9,
              "dewpoint_f": 53.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 15.9,
              "gust_kph": 25.6,
              "uv": 6
            },
            {
              "time_epoch": 1689357600,
              "time": "2023-07-14 21:00",
              "temp_c": 20.9,
              "temp_f": 69.6,
              "is_day": 1,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 11,
              "wind_kph": 17.6,
              "wind_degree": 301,
              "wind_dir": "WNW",
              "pressure_mb": 1016,
              "pressure_in": 30.01,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 57,
              "cloud": 27,
              "feelslike_c": 20.9,
              "feelslike_f": 69.6,
              "windchill_c": 20.9,
              "windchill_f": 69.6,
              "heatindex_c": 20.9,
              "heatindex_f": 69.6,
              "dewpoint_c": 12.1,
              "dewpoint_f": 53.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 16.6,
              "gust_kph": 26.6,
              "uv": 6
            },
            {
              "time_epoch": 1689361200,
              "time": "2023-07-14 22:00",
              "temp_c": 19.8,
              "temp_f": 67.6,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 302,
              "wind_dir": "WNW",
              "pressure_mb": 1017,
              "pressure_in": 30.02,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 62,
              "cloud": 31,
              "feelslike_c": 19.8,
              "feelslike_f": 67.6,
              "windchill_c": 19.8,
              "windchill_f": 67.6,
              "heatindex_c": 19.8,
              "heatindex_f": 67.6,
              "dewpoint_c": 12.4,
              "dewpoint_f": 54.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 1
            },
            {
              "time_epoch": 1689364800,
              "time": "2023-07-14 23:00",
              "temp_c": 19.5,
              "temp_f": 67.1,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 7.8,
              "wind_kph": 12.6,
              "wind_degree": 296,
              "wind_dir": "WNW",
              "pressure_mb": 1017,
              "pressure_in": 30.03,
              "precip_mm": 0,
              "precip_in": 0,
              "humidity": 65,
              "cloud": 26,
              "feelslike_c": 19.5,
              "feelslike_f": 67.1,
              "windchill_c": 19.5,
              "windchill_f": 67.1,
              "heatindex_c": 19.5,
              "heatindex_f": 67.1,
              "dewpoint_c": 12.9,
              "dewpoint_f": 55.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.1,
              "gust_kph": 19.4,
              "uv": 1
            }
          ]
        }
      ]
    }
  },
  error: false,
  loading: true,
}

export const forecastWeatherSlice = createSlice({
  name: 'forecastWeatherSlice',
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder.addCase(setForecastWeatherAsync.pending, (state: IForecastWeather): IForecastWeather => {
      state.loading = true;
      state.error = false;
      return state;
    });
    builder.addCase(setForecastWeatherAsync.rejected, (state: IForecastWeather): IForecastWeather => {
      state.loading = false;
      state.error = false;
      return state;
    });
    builder.addCase(setForecastWeatherAsync.fulfilled, (_: IForecastWeather, { payload }: PayloadAction<IForecastWeatherData>): IForecastWeather => {
      return {
        error: false,
        data: payload,
        loading: false,
      };
    });
  },
});

export const setForecastWeatherAsync = createAsyncThunk("forecastWeather/setForecastWeather", async (payload: string): Promise<IForecastWeatherData> => {
	const response = await forecastWeatherAPI.get(payload);
  if(response) {
    return response;
  } else {
    flashMessage("Smth went wrong", "Pls contact us", MessagesTypes.WARNING, FlashMessageBackgroundColors.WARNING, FlashMessageColors.WARNING);
    throw "Error"
  }
});

export default forecastWeatherSlice.reducer;